### ISSUE TITLE
[ENHANCEMENT] ~Duplicate from discord~ Void log upload & health monitor

### ISSUE THREAD

**Issue by LudoDash** [autumncpp/void-issues#10]
This is a Duplicate from the discord just so it helps with Azur moving everything to Github

### From the past month, I have been in here, I have noticed people have trouble finding the void logs.

**so here's a few cool suggestions:**

- Add a button called "Submit Void Log" to the void loader
which when clicked, would upload the latest void log.
and the log name would be changed to their discord ID/name for easy searching.

> I feel like it would greatly improve the efficiency of debugging and assisting people.

⠀
⠀
⠀
⠀
⠀
**And below is maybe something to add in the future.**

> _(Having it as an optional install would probably improve user trust in your program as it would be their choice to install the background process)_

⠀
⠀
⠀
### creating a small background application that monitors the status of Vrchat. (And ONLY runs when Vrchat is running)
eg:
- when Vrchat launches the monitor application would as well.

- And if you were to close Vrchat the monitor would close
⠀
⠀
⠀
⠀

### BUUUUT

If Vrchat was to unexpectedly exit, the monitor wouuuulllld

- upload the latest Void log,

- upload the latest Vrchat log(toggleable)

- upload last 3 avatars loaded from the avatar logs

⠀
⠀
- Once completed the program would then close itself.
⠀
⠀
⠀
⠀

possibly also have the option for the program to automatically attempt to relaunch Vrchat (after 2 or 3 seconds).
and if it were to fail 2 times on attempting to launch Vrchat.
it would mark the uploaded files with a possible bug

**Comment by LudoDash** [comment]
# Addition
- measure the average framerate of the users vrchat and save the average to the config or a file.

- allow the user to manually trigger void to take a average framerate measure and save it


# On Avatar Load
- when an avatar is loaded it first saves the ID to the avatar log file.

- Then after the avatar has loaded, void will take a average fps reading.

- Then save the fps value to the end of the avatar ID log.

> eg: the log would look something like this
```
avtr_dic83ba6c-83hs14-4daa-0175-51907227dd8d **[F:63]**
```

- If the framerate is a certain threshold below the average normal framerate measured. Void would automatically blacklist the avatar. [Allow user to toggle this feature]

**Comment by notunixian** [comment]
> # Addition
> * measure the average framerate of the users vrchat and save the average to the config or a file.
> * allow the user to manually trigger void to take a average framerate measure and save it
> 
> # On Avatar Load
> * when an avatar is loaded it first saves the ID to the avatar log file.
> * Then after the avatar has loaded, void will take a average fps reading.
> * Then save the fps value to the end of the avatar ID log.
> 
> > eg: the log would look something like this, (the F_avg would be a reading void would take apon entering a world and loading all current avatars successfully.
> > (It would append the avatar log after it succeeds)
> 
> (F would be the framerate after loading the avatar)
> 
> ```
> avtr_dic83ba6c-83hs14-4daa-0175-51907227dd8d  **[F_avg:63,F_:61]**
> ```
> 
> * If the framerate is a certain threshold below the average normal framerate measured. Void would automatically blacklist the avatar. [Allow user to toggle this feature]
> 
> > this is what it would look like when void would automatically blacklist an avatar which caused a severe frame drop.
> 
> ```
> avtr_dic83ba6c-83hs14-4daa-0175-51907227dd8d **[F_avg:63 , F:11]** (Auto_Blacklisted)
> ```
> 
> > I have not personally seen this implemented anywhere, so void might even be the first!

like you said at the bottom of your post, this has been implemented in other clients (svh) but in a different way of hiding unoptimized avatars (pretty sure it's just a hard limit on polygons/meshes/dyn bones or other things that would lower your fps) or avatars that would drastically lower your fps.

but i also think this implementation would be hit or miss because you can always have sudden fps dips in vrchat and there could be a edge case where you have a fps dip or load something that causes your fps to lower and suddenly someone's avatar is now blacklisted

**Comment by LudoDash** [comment]
*I stated Average Fps

**Comment by LudoDash** [comment]
> > # Addition
> > 
> > * measure the average framerate of the users vrchat and save the average to the config or a file.
> > * allow the user to manually trigger void to take a average framerate measure and save it
> > 
> > # On Avatar Load
> > 
> > * when an avatar is loaded it first saves the ID to the avatar log file.
> > * Then after the avatar has loaded, void will take a average fps reading.
> > * Then save the fps value to the end of the avatar ID log.
> > 
> > > eg: the log would look something like this, (the F_avg would be a reading void would take apon entering a world and loading all current avatars successfully.
> > > (It would append the avatar log after it succeeds)
> > 
> > 
> > (F would be the framerate after loading the avatar)
> > ```
> > avtr_dic83ba6c-83hs14-4daa-0175-51907227dd8d  **[F_avg:63,F_:61]**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * If the framerate is a certain threshold below the average normal framerate measured. Void would automatically blacklist the avatar. [Allow user to toggle this feature]
> > 
> > > this is what it would look like when void would automatically blacklist an avatar which caused a severe frame drop.
> > 
> > 
> > ```
> > avtr_dic83ba6c-83hs14-4daa-0175-51907227dd8d **[F_avg:63 , F:11]** (Auto_Blacklisted)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > I have not personally seen this implemented anywhere, so void might even be the first!
> 
> like you said at the bottom of your post, this has been implemented in other clients (svh) but in a different way of hiding unoptimized avatars (pretty sure it's just a hard limit on polygons/meshes/dyn bones or other things that would lower your fps) or avatars that would drastically lower your fps.
> 
> but i also think this implementation would be hit or miss because you can always have sudden fps dips in vrchat and there could be a edge case where you have a fps dip or load something that causes your fps to lower and suddenly someone's avatar is now blacklisted

**Average FPS**

**Comment by LudoDash** [comment]
> 

You also have Corrupted asset bundles & new ways of crashing that are always being created.

The average Fps would be measured After the avatar has loaded, not during
