### ISSUE TITLE
[ENHANCEMENT] Copy instance ID on world instance page

### ISSUE THREAD

**Issue by SouljaVR** [autumncpp/void-issues#14]
**Describe the feature/suggestion you'd like**

Could we get a button on world pages that lets us copy the world instance ID? thank you!

**Comment by Azurilex** [comment]
Please use the format provided when creating an issue.

**Comment by notunixian** [comment]
done by using this mod https://github.com/Saya-de/InstanceCopy
but yea this would be a nice feature

**Comment by autumncpp** [comment]
https://github.com/Saya-de/InstanceCopy

I would just use that mod.
