### ISSUE TITLE
[ENHANCEMENT] Extra Camera Features

### ISSUE THREAD

**Issue by SerDubstepCat** [autumncpp/void-issues#18]
**Describe the feature/suggestion you'd like**
The ability to have a togglable (and bindable) third-person and free camera.
If this gets added also possibly the feature to attach our camera to other players heads.

**Additional context**
(I know Teo blows but it gives such good functionality)
Third-person camera:
![image](https://user-images.githubusercontent.com/48300512/154375163-5f6e175f-ad8a-43c8-99d1-aaa15ddb5430.png)
Free-camera / Attach Camera:
![image](https://user-images.githubusercontent.com/48300512/154375893-44361efb-e20c-4d59-98d8-d6458aef5b9c.png)

**Comment by Azurilex** [comment]
Thirdperson was implemented in Build 59, I'll add freecam soon.
