### ISSUE TITLE
[ENHANCEMENT] Nameplate info changes/improvements 

### ISSUE THREAD

**Issue by The-Fuz** [autumncpp/void-issues#29]
**Describe the feature/suggestion you'd like**
- Platform indicator differentiates between PCVR and Quest (would show Q or QU if on quest)
- Prevent over rendering of other mods/part of the game, currently covers snaxy tags and the quest indicator, think it could be solved if the info moved down when you open the menu

**Additional context**

Quest covered up 
![image](https://user-images.githubusercontent.com/99560779/158246357-e8d385de-29ed-49a1-b0ee-95d4f72c8b74.png)

Snaxy covered up
![image](https://user-images.githubusercontent.com/99560779/158246507-49de5826-3dec-4ac7-bb19-459cfe31cd8d.png)

**Comment by Azurilex** [comment]
Ah, okay. Quest stuff I implemented a bit ago, I'll be sure to fix this overlapping soon.
