### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by owoahontop** [autumncpp/void-issues#42]
**Describe the bug**
Debug log became not compatible with another client works with only void but as soon as I load in something else no detection appears. I can still see the log and everything is fine just nothing appears in it.

**To Reproduce** 
Just loading in another client 

**Expected behavior**

**Screenshots**
https://gyazo.com/1dbe1695921a07e8bf2d2eb48ab04f80 
https://gyazo.com/cb8f616531b4dd0887d8f7205bf6eab8

**Additional context**
I know it's not a void issue because it works with JUST void but is it just my client or other clients too compatibility broken aswell?

**Comment by Nyxxem** [comment]
Can confirm Noto does affect the log for void.

**Comment by Azurilex** [comment]
Can you please provide screenshots of this effected by the bug?

**Comment by owoahontop** [comment]
> 

What kind of screenshots would you like exactly nothing happens really in game except just those detections don't arrive to the debug
