### ISSUE TITLE
[ENHANCEMENT] Nameplate info compatibility with ProPlates/Snaxy

### ISSUE THREAD

**Issue by SouljaVR** [autumncpp/void-issues#49]
Could we get a compatibility layer added for the proplates mod? SnaxyTags has its own compatibility layer too, so its important it doesnt conflict with either. If the nameplate info could be pushed above the nameplate instead of below it when proplates is detected that would be sweet, thank you!

**Comment by autumncpp** [comment]
this will not be added.
