### ISSUE TITLE
[ENHANCEMENT] Whitelist avis without having to rejoin

### ISSUE THREAD

**Issue by Tamol55** [autumncpp/void-issues#52]
**Describe the feature/suggestion you'd like**
Would love to be able to whitelist avi's without having to rejoin the world as a fair good ammount of avis looks pretty bad without being whitelisted.

**Additional context**
Rejoning the world everytime a new friend joins or if people are showing of multiple avi's can be a bit tedious and would love for this to be solved if its possible. PS: the last update is AMAZING!

**Comment by autumncpp** [comment]
This is done in build 101.
