### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by CheshireVR** [autumncpp/void-issues#54]
**Describe the feature/suggestion you'd like**
Fix the player attach please 

**Additional context**
It's kinda weird to have it so that once you attach yourself to someone they have to be completely still to detach yourself from them. Also if you attach yourself to someone in the black cat, they have to go back to the spawn lobby for you to detach. If they take you into a private room (which you can't stop if they're moving) you are just stuck on them unless you reset your game. Maybe I'm missing something but it's not as good as I'd hoped

**Comment by autumncpp** [comment]
This is fixed.
