### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by WasItSilent** [autumncpp/void-issues#56]
A button that will crash only a specific person using a crasher specific to the victim's platform

Possibly giving this feature its own tab where you can configure the crasher, replace what crashers you have selected back to void's default, and see what current crashers you have as your current crasher. Ik that might be confusing but that's it.

**Comment by autumncpp** [comment]
Unfortunately I won't be adding this due to the possibility of it being "unsafe". Target crashing requires that you block and unblock everyone in the instance besides the target, this can possibly effect your trust rank in a negative manner.
