### ISSUE TITLE
[BUG] Reduce Bad Activity limits/disables remote AV3 parameter sync

### ISSUE THREAD

**Issue by SouljaVR** [autumncpp/void-issues#59]
**Describe the bug**
When RBA is enabled, you cant see peoples toggles change. They sync for a few seconds then it stops working.

**To Reproduce**
Turn on RBA and ask a remote player to switch through their toggles. After about 10 seconds they get completely limited and dont work anymore.

**Expected behavior**
AV3 parameters should sync at full speed, especially with the new 256bit parameter update allowing for things like face tracking etc. to be viable now. It is important these parameters sync smoothly and accurately.

VOID ON TOPPPPPPP Thank you.

**Comment by autumncpp** [comment]
Should be good now.
