### ISSUE TITLE
[BUG] Karma client-compatibility

### ISSUE THREAD

**Issue by LilKhloe** [autumncpp/void-issues#60]
**Describe the bug**
When trying to inject Void while using Karma client, a runtime error will occur causing the game to crash.
This happens regardless of injecting Void during VRChat initializing (autoload) or after it is fully loaded.
**To Reproduce**
Run Karma client and inject Void

**Expected behavior**
For Void to successfully inject alongside Karma without causing any errors/crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/106421946/170826100-3d7d3a17-2891-4e86-af0a-0d70b902c7c3.png)

**Additional context**
Before Karma's latest update, the client (Karma) would not finish fully loading unless the quick menu was opened.
This allowed the user to successfully inject Void before Karma, allowing everything to work.
This has since been fixed and Karma now properly starts with VRChat. Injecting Void after this update causes the error described above. I'm unsure if this is even possible to fix without Kama contributing but I am adding the issue regardless.
#

**Comment by autumncpp** [comment]
Thanks for reporting this. Unfortunately, I'm going to have to ask you to please report this to Karma's dev team. They made a change that resulted in this exception, and I honestly don't want to download & run their custom Melonloader binaries just to debug an issue that they caused.
