### ISSUE TITLE
[ENHANCEMENT] Fix Game Modules/Add More

### ISSUE THREAD

**Issue by TheSleepySage** [autumncpp/void-issues#66]
**Describe the feature/suggestion you'd like**
Details here
The Murder Mystery Game Modules Don't Seem To Work Correctly Same For FBT HEAVEN
**Additional context**

**Comment by Grobitalks** [comment]
A cheat for magic freeze tag and amongus would be nice

**Comment by LudoDash** [comment]
> A cheat for magic freeze tag and amongus would be nice

put in an enhancement request with the specifics, It might happen

**Comment by LudoDash** [comment]
> **Describe the feature/suggestion you'd like** Details here The Murder Mystery Game Modules Don't Seem To Work Correctly Same For FBT HEAVEN **Additional context** Add any other context or screenshots about the feature request here.

make sure you have "reduce bad activity" disabled save ur config then rejoin the world,
it breaks game worlds sometimes.
