### ISSUE TITLE
[ENHANCEMENT] Toggle Anti-Avatar Crash and RBA for instance type

### ISSUE THREAD

**Issue by LilKhloe** [autumncpp/void-issues#68]
**Describe the feature/suggestion you'd like**
Add toggles to enable or disable Anti-Avatar Crash and RBA for different instance types.

**Additional context**

**Comment by autumncpp** [comment]
This will not be added. I've put some thought into it, and instead I'm going to extend the VR Menu's configuration system to allow configuration switching from within VR. Once that's done, you'll be able to set up a separate config for this purpose.

**Comment by LilKhloe** [comment]
is there an eta on the menu config extension?
