### ISSUE TITLE
[BUG] Reduce Bad activity keeps avatar toggles from toggling properly

### ISSUE THREAD

**Issue by Grobitalks** [autumncpp/void-issues#69]
**Describe the bug**
When reduce Bad Activity is enabled, the toggles on the avatars from friends don't sync properly (i have them whitelisted).
Some are synced delayed, some don't toggle at all.

**To Reproduce**
Turn on RBA and ask a friend to switch clothing.

**Expected behavior**
Toggles sync properly and are visible.

**Screenshots**

**Additional context**

**Comment by autumncpp** [comment]
Fixed in build 103
