### ISSUE TITLE
[ENHANCEMENT] Self select whitelist while on VR?

### ISSUE THREAD

**Issue by yourkidiscussin** [autumncpp/void-issues#70]
i think its implanted or not so correct me or walk me through it. So sometimes i whitelist people or my self to whitelist to see the avi, and i have to walk through my pc just to pull up the desktop menu and manually whitelist. Maybe during VR you can add self select > and the whitelist? i know in fact when you select a user and scroll to them bottom you can whitelist,blacklist, TP objects/items ( correct if wrong). so again my idea is have a self select mode to whitelist. sorry if it doesnt make sense LOL

**Comment by LilKhloe** [comment]
You can already whitelist yourself, just go to the same menu as you would for other people.

**Comment by autumncpp** [comment]
Here tab->Click yourself->Whitelist Avatar
