### ISSUE TITLE
[Bots, even though it's probably been suggested already]

### ISSUE THREAD

**Issue by NIneFox7097** [autumncpp/void-issues#71]
**Describe the feature/suggestion you'd like**
application bots, with better features than serenity, why not make this an all in one client am i right :)

**Additional context**
![jo4be464](https://user-images.githubusercontent.com/54329102/178392102-89f69e93-4e6d-47aa-8e53-eb653d1fb30a.png)
![va50qbqn](https://user-images.githubusercontent.com/54329102/178392109-3494f479-97e5-4cf9-9b95-a7a637c46030.png)
![ov30q979](https://user-images.githubusercontent.com/54329102/178392111-eb185a8f-d09c-44f2-8a3c-b287c3f5bed9.png)
i'm aware i have multiple clients that have bots, but it'd be nice to have an all in one client :)

**Comment by autumncpp** [comment]
No
