### ISSUE TITLE
[ENHANCEMENT] Hide console window

### ISSUE THREAD

**Issue by K4waiiNeko** [autumncpp/void-issues#73]
**Describe the feature/suggestion you'd like**
Ability to hide console window

**Additional context**
Toggle could just be thrown under "configuration" tab

**Comment by autumncpp** [comment]
This can cause issues when running Void alongside something like Melonloader, at it won't be added due to that fact.

**Comment by K4waiiNeko** [comment]
I mean VRTool has the option and it doesn't cause issues whatsoever when ran alongside melonloader, and melonloader has a launch option to disable it as well ( --melonloader.hideconsole ). I see absolutely 0 reason you wouldn't want to implement it.
