### ISSUE TITLE
[BUG] Reduce Anti-Avatar Crash False Positives

### ISSUE THREAD

**Issue by Tamol55** [autumncpp/void-issues#76]
**Describe the feature/suggestion you'd like**
Add an option to whitelist anyone you have "shown avatar"

**Additional context**

**Comment by autumncpp** [comment]
This will not be added, primarily because this will confuse people and just adds to the idea of a "config issue". Just whitelist one's avatar, you shouldn't need to do it that much.

**Comment by Tamol55** [comment]
how about whitelist user instead of avi?

**Comment by Tamol55** [comment]
I need to whitelist fairly often

**Comment by autumncpp** [comment]
> how about whitelist user instead of avi?

I'm still going to pass on that as that could still get abused. I'll also point out that Void's avatar scanning is done pretty low level and there isn't any User ID attached to the avatar when the scanning is done, in fact, Void has to do some relatively "hacky" stuff to even pull the Avatar ID from the object.

**Comment by autumncpp** [comment]
> I need to whitelist fairly often

Feel free to send some Avatar ID's that you need to whitelist a lot and I can look and see why they're getting false flagged.

**Comment by Tamol55** [comment]
Its because they are heavy booth avis.
I am sad that you won't add this but thanks for replying. I can still find you some IDs tomorrow if you want

**Comment by autumncpp** [comment]
> Its because they are heavy booth avis.
> I am sad that you won't add this but thanks for replying. I can still find you some IDs tomorrow if you want

Please do, I'll take a look at them.

**Comment by LilKhloe** [comment]
> > Its because they are heavy booth avis.
> > I am sad that you won't add this but thanks for replying. I can still find you some IDs tomorrow if you want
> 
> Please do, I'll take a look at them.

Can you also make the speech to text bubble I showed you not get destroyed by avatar scanning.

**Comment by autumncpp** [comment]
> > > Its because they are heavy booth avis.
> > > I am sad that you won't add this but thanks for replying. I can still find you some IDs tomorrow if you want
> > 
> > 
> > Please do, I'll take a look at them.
> 
> Can you also make the speech to text bubble I showed you not get destroyed by avatar scanning.

Can you provide me with an avatar id for an avatar that has this?

**Comment by LilKhloe** [comment]
I made my avatar temporarily public for you to check it, but you won't be able to use the textbox without access to the external app. avtr_06c57bc0-4bf6-49c7-a3e5-0dcc18e18737

**Comment by autumncpp** [comment]
> I made my avatar temporarily public for you to check it, but you won't be able to use the textbox without access to the external app. avtr_06c57bc0-4bf6-49c7-a3e5-0dcc18e18737

Thank you, I am looking at it now.

**Comment by autumncpp** [comment]
(didn't mean to close)

**Comment by autumncpp** [comment]
> I made my avatar temporarily public for you to check it, but you won't be able to use the textbox without access to the external app. avtr_06c57bc0-4bf6-49c7-a3e5-0dcc18e18737

This avatar's shaders will work properly without whitelisting in the next update. 👍

**Comment by LilKhloe** [comment]
Another avatar that gets crippled by scanning > avtr_e9875620-839a-4468-9b80-11a0d920ab45
This avatar will be used a lot in the upcoming month so it would prob help

**Comment by Tamol55** [comment]
avtr_d0af29ba-e060-4ea1-a29f-2da283bb4a06
avtr_bed372c6-4a3e-47d4-8236-5a46bd003e96
avtr_d0af29ba-e060-4ea1-a29f-2da283bb4a06
avtr_f77d8e7f-98c0-4054-8fb3-178b11aa87f3
avtr_3552c9e7-fb07-4a50-ab05-55ab34c54656
avtr_e5972e32-0770-48ad-945b-aea9e38bb111
avtr_128be217-ce6f-4a00-85b4-5c13f012be52
avtr_f0a5dcb9-dcec-4ea4-a229-19d42615b29e
avtr_2b996680-5c09-4311-82ef-d7f63bfef0d4


Most of the avi's are private avis i've noticed but here is some examples anyway

**Comment by autumncpp** [comment]
build 106 fixed a lot of these
