### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Icey-Glitch** [autumncpp/void-issues#77]
**Describe the bug**
you can inject void multiple times on the same game, it also spawns multiple imgui menus, this is especially annoying if you are running two instances of the game and are trying to inject on one of them and it keep injecting on the same game.
**To Reproduce**
Steps to reproduce the behavior: press the inject button more than once

**Expected behavior**
to only inject once.

**Screenshots**
![VRChat_kxqn8NviXi](https://user-images.githubusercontent.com/67936038/179364390-2aa55d95-c9eb-42b4-9043-1a376357f5c9.png)

**Additional context**
i don't even know if this was possible before but if not then now you know

**Comment by Icey-Glitch** [comment]
![VRChat_YJcD2A7exw](https://user-images.githubusercontent.com/67936038/179364454-a894c9c7-cda0-404e-afe9-03e83045ae8d.png)
just found that this happens too

**Comment by autumncpp** [comment]
Click the inject button once.
